### ISSUE TITLE
Unhandled Exception - Navigation to Stats (1.3.0)

### ISSUE THREAD

**Issue by Ostabo** [the-hideout/TarkovMonitor#55]
![grafik](https://github.com/the-hideout/TarkovMonitor/assets/34040518/bee6d103-4ac8-4025-b8d2-5d0dc31cd388)

German equivalent of unhandled exception, after clicking on the new stats navigation

I assume the path is not set

Details:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString)
   at TarkovMonitor.Stats..cctor() in TarkovMonitor\Stats.cs:line 18
```

**Comment by Razzmatazzz** [comment]
It can't find your LocalApplicationData folder. Is there anything unusual about your setup that would prevent an app from finding standard Windows configuration folders?

**Comment by bitpushr** [comment]
I get this as well, nothing unusual about my setup. Can reproduce by fresh installing it on a bone stock Windows 11 VM.

**Comment by Razzmatazzz** [comment]
If you Run "%LOCALAPPDATA%", does it open a folder, and if so, is there a TarkovMonitor folder within that folder?

**Comment by Ostabo** [comment]
Appdata/Local
![grafik](https://github.com/the-hideout/TarkovMonitor/assets/34040518/fdd18c57-e99c-4078-95fc-8101c620ce7e)
-> TarkovMonitor
![grafik](https://github.com/the-hideout/TarkovMonitor/assets/34040518/cc9f04b8-95ee-4402-b6d7-b74989bedc6c)
-> TarkovMonitor_Path_gu5...
![grafik](https://github.com/the-hideout/TarkovMonitor/assets/34040518/5031c6a3-f5ff-4c4e-b87e-55d8cec6e3ad)


The TarkovMonitor folder is present and contains 2 subfolders - 1 containing another two subfolders for the versions I had installed, and one only containing the current 1.2.3 version i switched back to

**Comment by bitpushr** [comment]
> Appdata/Local ![grafik](https://private-user-images.githubusercontent.com/34040518/303935760-fdd18c57-e99c-4078-95fc-8101c620ce7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NzM5ODcsIm5iZiI6MTcwNzY3MzY4NywicGF0aCI6Ii8zNDA0MDUxOC8zMDM5MzU3NjAtZmRkMThjNTctZTk5Yy00MDc4LTk1ZmMtODEwMWM2MjBjZTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE3NDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMTI2NjZiNzJjZDY4NDRlYmE5MWFmZWU0ZDZmMmYzYmIyM2M3MDdiMGE1MjgwNmYzN2ZmMTI3ZmM4YWFiNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SMy5sSDybhnRgsamW1wzlm-8b8DV9lmTOEq7pDxyH8Q) -> TarkovMonitor ![grafik](https://private-user-images.githubusercontent.com/34040518/303935786-cc9f04b8-95ee-4402-b6d7-b74989bedc6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NzM5ODcsIm5iZiI6MTcwNzY3MzY4NywicGF0aCI6Ii8zNDA0MDUxOC8zMDM5MzU3ODYtY2M5ZjA0YjgtOTVlZS00NDAyLWI2ZDctYjc0OTg5YmVkYzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE3NDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ODNlZTUwNGRlODZkNjhiYWQyNjU0NDE1ZjRkNjRhZTcwNGE0OTE4NDg4MWNkYmY4MTNlYWUwZTdhNGU0MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EfdGPRsSs_goLoEdboHHSpUAj23F_SS6qEta9kfZuKQ) -> TarkovMonitor_Path_gu5... ![grafik](https://private-user-images.githubusercontent.com/34040518/303935942-5031c6a3-f5ff-4c4e-b87e-55d8cec6e3ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NzM5ODcsIm5iZiI6MTcwNzY3MzY4NywicGF0aCI6Ii8zNDA0MDUxOC8zMDM5MzU5NDItNTAzMWM2YTMtZjVmZi00YzRlLWI4N2UtNTVkOGNlYzZlM2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE3NDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNmJjYmRmODA3NTE0MTFjMjg2MDgxYTZjM2U5ODgzM2E2ODAxNDFhNGQxMzBhODVjZmIxOGRjMDFiYzkzMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QFI6XRzt64NKzdB-vHlpkMHspBl2f8crbShtYrJUwPY)
> 
> The TarkovMonitor folder is present and contains 2 subfolders - 1 containing another two subfolders for the versions I had installed, and one only containing the current 1.2.3 version i switched back to

Same here

**Comment by Razzmatazzz** [comment]
For some users, `Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)` is resolving to null. It should give the path for the user's %LocalAppData% folder. That path is used to create/access the local sqlite database that the app uses for storing raid and flea sales data for displaying statistics. Because it can't resolve that path, the database can't be created, and anything that would access the database causes the app to crash. These crash triggers are:

- Viewing the Stats page
- Selling an item on the flea
- Loading into a raid

**Comment by Razzmatazzz** [comment]
Can someone experiencing this issue please try this build:
https://github.com/the-hideout/TarkovMonitor/actions/runs/7865137539/artifacts/1236961902

**Comment by Vaelek** [comment]
I cloned the repo to try and step through it to see what might be happening. Malwarebytes wants to quarantine the DLL, but after allowing that, it seems to work fine when I build it myself..

**Comment by Vaelek** [comment]
> Can someone experiencing this issue please try this build: https://github.com/the-hideout/TarkovMonitor/actions/runs/7865137539/artifacts/1236961902

This build crashes for me

**Comment by Razzmatazzz** [comment]
Does it happen to work if you run as administrator?

**Comment by Vaelek** [comment]
> Does it happen to work if you run as administrator?

Negative

**Comment by Razzmatazzz** [comment]
I know where the error is occurring, I just can't figure out why some PCs fail to resolve these appdata folders properly.

**Comment by Vaelek** [comment]
As I mentioned above, if I build the solution myself with no changes, I can execute the build without errors. You have an additional packaging step that I do not know, but perhaps something in that is causing the issue?

**Comment by Razzmatazzz** [comment]
Oh yeah I think I might know what's going on.

**Comment by Razzmatazzz** [comment]
This should be resolved in the latest release.
