### ISSUE TITLE
Error when sold an LedX

### ISSUE THREAD

**Issue by M3ragon** [the-hideout/TarkovMonitor#70]
```log
Error parsing Notifications log data 2024-04-14 21:34:54.144 +02:00|Info|push-notifications|LongPollingWebSocketRequest result Count:945 MessageType:Text
2024-04-14 21:34:54.144 +02:00|Info|push-notifications|LongPollingWebSocketRequest received:945
2024-04-14 21:34:54.144 +02:00|Info|push-notifications|Got notification | ChatMessageReceived
{
  "type": "new_message",
  "eventId": "661c2fde50ca0dbc3602e7ea",
  "dialogId": "5ac3b934156ae10c4430e83c",
  "message": {
    "_id": "661c2fde7646456caa05e0c48",
    "uid": "5ac3b934156ae10c4430e83c",
    "type": 4,
    "dt": 1713123294,
    "text": "",
    "templateId": "5bdabfb886f7743e152e867e 0",
    "systemData": {
      "buyerNickname": "18cmNohead",
      "soldItem": "5c0530ee86f774697952d952",
      "itemCount": 1
    },
    "items": {
      "stash": "661c2fde7646456caa05e0c5",
      "data": [
        {
          "_id": "661c2fde7646456caa05e0bf",
          "_tpl": "5449016a4bdc2d6f028b456f",
          "upd": {
            "StackObjectsCount": 500000
          },
          "parentId": "661c2fde7646456caa05e0c5",
          "slotId": "main"
        },
        {
          "_id": "661c2fde7646456caa05e0c0",
          "_tpl": "5449016a4bdc2d6f028b456f",
          "upd": {
            "StackObjectsCount": 500000
          },
          "parentId": "661c2fde7646456caa05e0c5",
          "slotId": "main"
        },
        {
          "_id": "661c2fde7646456caa05e0c1",
          "_tpl": "5449016a4bdc2d6f028b456f",
          "upd": {
            "StackObjectsCount": 300000
          },
          "parentId": "661c2fde7646456caa05e0c5",
          "slotId": "main"
        }
      ]
    },
    "maxStorageTime": 604800,
    "profileChangeEvents": [],
    "hasRewards": true
  }
}
2024-04-14 21:34:54.144 +02:00|Info|push-notifications|NotificationManager.ProcessMessage | Received notification: Type: ChatMessageReceived, Time: 0, Duration: Default, ShowNotification: False
2024-04-14 21:34:54.161 +02:00|Info|push-notifications|LongPollingWebSocketRequest result Count:153 MessageType:Text
2024-04-14 21:34:54.161 +02:00|Info|push-notifications|LongPollingWebSocketRequest received:153
2024-04-14 21:34:54.161 +02:00|Info|push-notifications|Got notification | RagfairOfferSold
{
  "type": "RagfairOfferSold",
  "eventId": "661c2fde56530738b6096569",
  "offerId": "661c2fda1d5322adba10eda18",
  "handbookId": "5c0530ee86f774697952d952",
  "count": 1
}
2024-04-14 21:34:54.161 +02:00|Info|push-notifications|NotificationManager.ProcessMessage | Received notification: Type: RagfairOfferSold, Time: 0, Duration: Default, ShowNotification: True
: An item with the same key has already been added. Key: 5449016a4bdc2d6f028b456f
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at TarkovMonitor.FleaSoldMessageEventArgs.get_ReceivedItems() in TarkovMonitor\LogMessageTypes.cs:line 244
   at TarkovMonitor.Stats.AddFleaSale(FleaSoldMessageEventArgs e) in TarkovMonitor\Stats.cs:line 86
   at TarkovMonitor.MainBlazorUI.Eft_FleaSold(Object sender, FleaSoldMessageEventArgs e) in TarkovMonitor\MainBlazorUI.cs:line 551
   at TarkovMonitor.GameWatcher.GameWatcher_NewLogData(Object sender, NewLogDataEventArgs e) in TarkovMonitor\GameWatcher.cs:line 400
```

i got this error, when someone bougth my ledx

**Comment by Razzmatazzz** [comment]
This is fixed in the latest release. Thanks for reporting!

**Comment by JanK118** [comment]
I don't know, if it is really fixed, because I got this message several times, when i was selling magazines...

`Error parsing Notifications log data 2024-05-25 03:42:22.374 +02:00|Info|push-notifications|LongPollingWebSocketRequest result Count:628 MessageType:Text
2024-05-25 03:42:22.374 +02:00|Info|push-notifications|LongPollingWebSocketRequest received:628
2024-05-25 03:42:22.374 +02:00|Info|push-notifications|Got notification | ChatMessageReceived
{
  "type": "new_message",
  "eventId": "665141fe9e2b913a4c098e56",
  "dialogId": "5ac3b934156ae10c4430e83c",
  "message": {
    "_id": "665141fe73d5a582e90a486f50",
    "uid": "5ac3b934156ae10c4430e83c",
    "type": 4,
    "dt": 1716601342,
    "text": "",
    "templateId": "5bdabfb886f7743e152e867e 0",
    "systemData": {
      "buyerNickname": "XBttKJxan",
      "soldItem": "59d625f086f774661516605d",
      "itemCount": 2
    },
    "items": {
      "stash": "665141fe73d5a582e90a4870",
      "data": [
        {
          "_id": "665141fe73d5a582e90a486b",
          "_tpl": "5449016a4bdc2d6f028b456f",
          "upd": {
            "StackObjectsCount": 13332
          },
          "parentId": "665141fe73d5a582e90a4870",
          "slotId": "main"
        }
      ]
    },
    "maxStorageTime": 604800,
    "profileChangeEvents": [],
    "hasRewards": true
  }
}
2024-05-25 03:42:22.374 +02:00|Info|push-notifications|NotificationManager.ProcessMessage | Received notification: Type: ChatMessageReceived, Time: 0, Duration: Default, ShowNotification: False
2024-05-25 03:42:22.391 +02:00|Info|push-notifications|LongPollingWebSocketRequest result Count:153 MessageType:Text
2024-05-25 03:42:22.391 +02:00|Info|push-notifications|LongPollingWebSocketRequest received:153
2024-05-25 03:42:22.394 +02:00|Info|push-notifications|Got notification | RagfairOfferSold
{
  "type": "RagfairOfferSold",
  "eventId": "665141fe5ed1cde05e086c2d",
  "offerId": "66512a468ab1c5104f0d06003",
  "handbookId": "59d625f086f774661516605d",
  "count": 2
}
2024-05-25 03:42:22.394 +02:00|Info|push-notifications|NotificationManager.ProcessMessage | Received notification: Type: RagfairOfferSold, Time: 0, Duration: Default, ShowNotification: True
: SQL logic error
5 values for 6 columns
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at TarkovMonitor.Stats.Query(String query, Dictionary`2 parameters) in TarkovMonitor\Stats.cs:line 52
   at TarkovMonitor.Stats.AddFleaSale(FleaSoldMessageLogContent e, Profile profile) in TarkovMonitor\Stats.cs:line 62
   at TarkovMonitor.MainBlazorUI.Eft_FleaSold(Object sender, LogContentEventArgs`1 e) in TarkovMonitor\MainBlazorUI.cs:line 599
   at TarkovMonitor.GameWatcher.GameWatcher_NewLogData(Object sender, NewLogDataEventArgs e) in TarkovMonitor\GameWatcher.cs:line 440`
