### ISSUE TITLE
Keep getting these Error parsing Notifications log data

### ISSUE THREAD

**Issue by ULtimateUAV** [the-hideout/TarkovMonitor#78]
Error parsing Notifications log data 2024-05-29 18:13:19.761 +01:00|Info|push-notifications|LongPollingWebSocketRequest result Count:624 MessageType:Text
2024-05-29 18:13:19.761 +01:00|Info|push-notifications|LongPollingWebSocketRequest received:624
2024-05-29 18:13:19.761 +01:00|Info|push-notifications|Got notification | ChatMessageReceived
{
  "type": "new_message",
  "eventId": "665762305cf3d2d5020bb6eb",
  "dialogId": "5ac3b934156ae10c4430e83c",
  "message": {
    "_id": "665762304ee5dca6070191cf41",
    "uid": "5ac3b934156ae10c4430e83c",
    "type": 4,
    "dt": 1717002800,
    "text": "",
    "templateId": "5bdabfb886f7743e152e867e 0",
    "systemData": {
      "buyerNickname": "vcxw",
      "soldItem": "5938504186f7740991483f30",
      "itemCount": 1
    },
    "items": {
      "stash": "665762304ee5dca6070191d0",
      "data": [
        {
          "_id": "665762304ee5dca6070191cc",
          "_tpl": "5449016a4bdc2d6f028b456f",
          "upd": {
            "StackObjectsCount": 20000
          },
          "parentId": "665762304ee5dca6070191d0",
          "slotId": "main"
        }
      ]
    },
    "maxStorageTime": 1209600,
    "profileChangeEvents": [],
    "hasRewards": true
  }
}
2024-05-29 18:13:19.761 +01:00|Info|push-notifications|NotificationManager.ProcessMessage | Received notification: Type: ChatMessageReceived, Time: 0, Duration: Default, ShowNotification: False
2024-05-29 18:13:19.778 +01:00|Info|push-notifications|LongPollingWebSocketRequest result Count:153 MessageType:Text
2024-05-29 18:13:19.778 +01:00|Info|push-notifications|LongPollingWebSocketRequest received:153
2024-05-29 18:13:19.778 +01:00|Info|push-notifications|Got notification | RagfairOfferSold
{
  "type": "RagfairOfferSold",
  "eventId": "665762309f2563db360f0421",
  "offerId": "66576190e13350a0f30b67a88",
  "handbookId": "5938504186f7740991483f30",
  "count": 1
}
2024-05-29 18:13:19.778 +01:00|Info|push-notifications|NotificationManager.ProcessMessage | Received notification: Type: RagfairOfferSold, Time: 0, Duration: Default, ShowNotification: True
: SQL logic error
5 values for 6 columns
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at TarkovMonitor.Stats.Query(String query, Dictionary`2 parameters) in TarkovMonitor\Stats.cs:line 52
   at TarkovMonitor.Stats.AddFleaSale(FleaSoldMessageLogContent e, Profile profile) in TarkovMonitor\Stats.cs:line 62
   at TarkovMonitor.MainBlazorUI.Eft_FleaSold(Object sender, LogContentEventArgs`1 e) in TarkovMonitor\MainBlazorUI.cs:line 599
   at TarkovMonitor.GameWatcher.GameWatcher_NewLogData(Object sender, NewLogDataEventArgs e) in TarkovMonitor\GameWatcher.cs:line 440

**Comment by Razzmatazzz** [comment]
This was resolved by #76. Next release will include the fix.
