### ISSUE TITLE
Error parsing Notifications

### ISSUE THREAD

**Issue by PullGravs** [the-hideout/TarkovMonitor#79]
Error parsing Notifications log data 2024-05-30 16:11:19.660 -04:00|Info|push-notifications|LongPollingWebSocketRequest result Count:628 MessageType:Text
2024-05-30 16:11:19.660 -04:00|Info|push-notifications|LongPollingWebSocketRequest received:628
2024-05-30 16:11:19.660 -04:00|Info|push-notifications|Got notification | ChatMessageReceived
{
  "type": "new_message",
  "eventId": "6658dd6bcf993849eb117661",
  "dialogId": "5ac3b934156ae10c4430e83c",
  "message": {
    "_id": "6658dd6bd5ab20f7cc062d7e7",
    "uid": "5ac3b934156ae10c4430e83c",
    "type": 4,
    "dt": 1717099883,
    "text": "",
    "templateId": "5bdabfb886f7743e152e867e 0",
    "systemData": {
      "buyerNickname": "DaNtEG96xx",
      "soldItem": "57347d8724597744596b4e76",
      "itemCount": 1
    },
    "items": {
      "stash": "6658dd6bd5ab20f7cc062d7f",
      "data": [
        {
          "_id": "6658dd6bd5ab20f7cc062d7b",
          "_tpl": "5449016a4bdc2d6f028b456f",
          "upd": {
            "StackObjectsCount": 54420
          },
          "parentId": "6658dd6bd5ab20f7cc062d7f",
          "slotId": "main"
        }
      ]
    },
    "maxStorageTime": 604800,
    "profileChangeEvents": [],
    "hasRewards": true
  }
}
2024-05-30 16:11:19.660 -04:00|Info|push-notifications|NotificationManager.ProcessMessage | Received notification: Type: ChatMessageReceived, Time: 0, Duration: Default, ShowNotification: False
2024-05-30 16:11:19.680 -04:00|Info|push-notifications|LongPollingWebSocketRequest result Count:153 MessageType:Text
2024-05-30 16:11:19.680 -04:00|Info|push-notifications|LongPollingWebSocketRequest received:153
2024-05-30 16:11:19.680 -04:00|Info|push-notifications|Got notification | RagfairOfferSold
{
  "type": "RagfairOfferSold",
  "eventId": "6658dd6bb66afa475d0ad0a9",
  "offerId": "6658d87724c0f7b16e06ce5ea",
  "handbookId": "57347d8724597744596b4e76",
  "count": 1
}
2024-05-30 16:11:19.680 -04:00|Info|push-notifications|NotificationManager.ProcessMessage | Received notification: Type: RagfairOfferSold, Time: 0, Duration: Default, ShowNotification: True
: SQL logic error
5 values for 6 columns
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at TarkovMonitor.Stats.Query(String query, Dictionary`2 parameters) in TarkovMonitor\Stats.cs:line 52
   at TarkovMonitor.Stats.AddFleaSale(FleaSoldMessageLogContent e, Profile profile) in TarkovMonitor\Stats.cs:line 84
   at TarkovMonitor.MainBlazorUI.Eft_FleaSold(Object sender, LogContentEventArgs`1 e) in TarkovMonitor\MainBlazorUI.cs:line 599
   at TarkovMonitor.GameWatcher.GameWatcher_NewLogData(Object sender, NewLogDataEventArgs e) in TarkovMonitor\GameWatcher.cs:line 440

**Comment by Razzmatazzz** [comment]
What version are you running? This should have been fixed in the latest release.
