### ISSUE TITLE
Error Connecting with id #### (Tarkov DEV remote management  ID)

### ISSUE THREAD

**Issue by Shibalba** [the-hideout/TarkovMonitor#82]
If I close browser and PC goes to sleep this text appears when sleep ended in messages multiple times with the same timestamp

Error Connecting with id ####: The CancellationTokenSource has been disposed. at Websocket.Client.WebsocketClient.StartBackgroundThreadForSendingText() at Websocket.Client.WebsocketClient.StartInternal(Boolean failFast) at TarkovMonitor.SocketClient.Connect() in TarkovMonitor\SocketClient.cs:line 104

**Comment by Razzmatazzz** [comment]
I was only able to replicate this issue accidentally when my computer went idle overnight. Tarkov Monitor was acting like I wasn't connected to the internet. Some other apps had similar problems, but others could connect to the internet just fine. The issues were resolved by restarting my PC. I think this is an issue with Windows managing network connections when a PC idles/sleeps, and therefore not fixable.

**Comment by AmaniZandalari** [comment]
Got this error even after restarting my PC. 

Error Connecting with id ####: The CancellationTokenSource has been disposed.
   at Websocket.Client.WebsocketClient.StartBackgroundThreadForSendingText()
   at Websocket.Client.WebsocketClient.StartInternal(Boolean failFast)
   at TarkovMonitor.SocketClient.Connect() in TarkovMonitor\SocketClient.cs:line 103

**Comment by Jadaju** [comment]
I have the same problem, tried restarting PC as well as reinstalling TarkovMonitor.

**Comment by anatole1234** [comment]
Same thing here

**Comment by tarkovplayer** [comment]
please don't just comment "affects me" if you don't have any additional information to provide.
this is just notifying everyone subscribed to the issue without any benefit.
it's clear that this affects multiple users, which also includes me, and in the future i recommend just putting a reaction on the issue or in this case the first comment from today, to indicate that you're affected without having this notify everyone.

**Comment by Razzmatazzz** [comment]
The recent errors should be fixed now. There was a certificate issue on the backend that has been resolved.

**Comment by Jadaju** [comment]
> The recent errors should be fixed now. There was a certificate issue on the backend that has been resolved.

Seems fixed, thanks a lot.

**Comment by Kenishi99** [comment]
I am getting this error again for some reason.

**Comment by Razzmatazzz** [comment]
The way Tarkov Monitor connects to the remote control system has been significantly reworked, so this should no longer be an issue.
